# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - language: generic
      os: osx
      osx_image: xcode6.4
      env: TOXENV=py27
    - language: generic
      os: osx
      osx_image: xcode6.4
      env: TOXENV=py33
    - language: generic
      os: osx
      osx_image: xcode6.4
      env: TOXENV=py34
    - language: generic
      os: osx
      osx_image: xcode6.4
      env: TOXENV=py35
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=py27
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=py33
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=py34
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=py35
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=docs

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh

after_success:
  - ./.travis/upload_coverage.sh
