# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=py26
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=py27
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=py33
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=py34
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=py35
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=pypy
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=py27
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=py26
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=py27
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=pypy
    - language: generic
      os: osx
      osx_image: osx10.11
      env: TOXENV=py26
    - language: generic
      os: osx
      osx_image: osx10.11
      env: TOXENV=py27
    - language: generic
      os: osx
      osx_image: xcode7
      env: TOXENV=docs

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh

# after_success:
#   - ./.travis/upload_coverage.sh

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: dulaccc
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: dulaccc/igenstrings
#     condition: $TOXENV == py27
